### ISSUE TITLE
0.1.0 unable to run on Xcode Simulator

### ISSUE THREAD

**Issue by DJTB** [Rushabhshroff/flutter_system_proxy#13]
Dev issue, seems non-critical for production.
Occurs for me using iPhone 14 on Simulator and Flutter 3.10.6

0.1.0 still works for me using a real device (iPhone 13).
0.0.2 still works using iPhone 14 on Simulator and Flutter 3.10.6

```
Xcode build done.              18s
flutter_system_proxy/SwiftFlutterSystemProxyPlugin.swift:81: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Lost connection to device.
Exited
```

**Comment by sigis151** [comment]
the same crash appears after updating to Xcode 14.3.1 and works with 14.2

**Comment by Rushabhshroff** [comment]
@sigis151 @DJTB fixed this in 0.1.1. Please change the ref to 0.1.1 until the PR is merged

**Comment by DJTB** [comment]
Thanks for the quick turnaround, despite not being a hard blocker 🙇 
Appreciate the package so much for dealing with proxy headaches in flutter!
